### ISSUE TITLE
How to build without using pod?

### ISSUE THREAD

**Issue by alessionunzi** [ParsePlatform/ParseUI-iOS#163]
How can I build ParseUI.framework without using pod?
I dislike using pod when I can use git submodules and also I can't replace some of my submodules with pod so I don't want end up having more than one way to manage and update my project dependencies.

After commit 52f24116e2c139e65991ac98ad0e0eabdd6c8cb9 the ParseUI.xcodeproj doesn't build anymore the standalone ParseUI.framework. I solved checking out the previous commit but is of course not optimal, how could I solve without pod?

Thanks

**Comment by nlutsenko** [comment]
There are multiple ways to achieve this.
- Option 1: you can use the pre-built framework from the releases
- Option 2: continue using submodules, but add a run script phase to run `pod update` inside the submodule, which output you a Pods.xcodeproj in $REPO_ROOT/Pods. You can simply drag and drop that one into your project.

ParseUI had a requirement to run `pod update` from the beginning of times, since we pull in dependencies via Cocoapods. So sorry it broke you, but in the current world I would really encourage usage of Cocoapods for dependency management.
