### ISSUE TITLE
Facebook SSO not working with iOS9

### ISSUE THREAD

**Issue by msuprovici** [ParsePlatform/ParseUI-iOS#167]
I installed the latest Parse iOS SDK (v 1.8.5) and Facebook iOS SDK (v4.6.0).  I'm using the PFLogInViewController & PFSignUpViewController. Facebook SSO is no longer working.  When I select 'login with facebook', the app opens a browser and asks me for my credentials.  Prior to this change, it would switch to the Facebook app.  I followed Facebook's guide: Preparing Your Apps for iOS9.  Any advice here?

**Comment by nlutsenko** [comment]
The difference in behavior is due to iOS 9 app linking restrictions.
You can still control the behavior using `[PFFacebookUtils facebookLoginManager].loginBehavior` property, but generally - it will always try to open in-app browser using `SFSafariViewController`.

Since we are simply wrapping public Facebook SDK APIs - I would suggest filing an issue on `https://developers.facebook.com/bugs` if you want different default behavior, or simply controlling it yourself.

Let me know if this helps.
