### ISSUE TITLE
Duplicate class issues in parse.framework

### ISSUE THREAD

**Issue by guxiaocheng** [ParsePlatform/ParseUI-iOS#175]
Hi, I tried to install ParseUI by cocoapods last night, and I succeeded at the second time. When it's done and I tried to compile and run it, there's the duplicate error:
duplicate symbol _OBJC_METACLASS_$_PFUserFileCodingLogic in:
    /Users/xiaochenggu/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-bykofptbjfndecbirjzgzluowers/Build/Products/Debug-iphonesimulator/libParse.a(PFUserFileCodingLogic.o)
    /Users/xiaochenggu/Documents/iOSProject/parse-starter-project-1.9.0/ParseStarterProject-Swift/Parse.framework/Parse(PFUserFileCodingLogic.o)
ld: 823 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So it seems, I have duplicate class "PFUserFileCodingLogic" both in libParse.a and parse.framework. I tried to delete libParse but as soon as the project runs, it's automatically created and reported error.

**Comment by guxiaocheng** [comment]
By the way, I'm using Xcode 7 and Swift 2

**Comment by nlutsenko** [comment]
Hey @guxiaocheng, this might sound strange, but here is what happens:
- Looks like you are using a generic Swift starter project for iOS from https://parse.com/docs/downloads (97% confident assumption based on the log message above)
- That project already includes `Parse.framework` inside of it
- You are pulling in the same code via CocoaPods and compiling it into `libParse.a`
- Since the code is literally 100% the same - it gives you linker errors about duplicate symbols, since you are linking 2 static libraries (the framework that we bundle with it is static) with the same symbols

Solution: 
If you want to use Cocoapods - simply delete Parse.framework as well as any reference to it from inside the Xcode project, then rerun `pod install` (just to make sure) - and everything should be set. It also might be a good idea to clean derived data just to make sure, but not required.

Please note that CocoaPods flow also gives you an ability to start using Parse with, roughly, any existing project you have.

I hope this helps, please let me know if not or there is anything else.
