### ISSUE TITLE
Pods-ParseUI wont build with cocoapods 0.36.0.beta.2

### ISSUE THREAD

**Issue by skhavari** [ParsePlatform/ParseUI-iOS#51]
###### Environment

- cocoapods version 0.36.0.beta.2
- xcode Version 6.1.1 (6A2008a)
- this podfile

````
platform :ios, '8.1'

pod 'JSQMessagesViewController', '~> 6.1.3'
pod 'Parse', '~> 1.6.2'
pod 'ParseUI', '~> 1.1.0'
pod 'DateTools', '~> 1.5.0'
pod 'Alamofire', '~> 1.1'
pod 'SwiftyJSON', '~> 2.1.3'
````

###### Repro

1. Create a new single page iOS app with xcode, quit xcode
2. use the `Podfile` above and `pod install`
3. Open `<Project>.xcworkspace` and build

###### Expect

1. Project builds

###### Actual

1. Get 18 linker errors about undefined symbols for architecture x86_64 while building Pods-ParseUI

**Comment by skhavari** [comment]
potentially this issue?
https://www.parse.com/questions/undefined-symbols-for-architecture-x86_64-fbtokeninformationexpirationdatekey

**Comment by nlutsenko-fb** [comment]
I believe no - that one is from 11 month ago :(
First thing that comes to my mind is that cocoapods 0.36.0 automatically opt-ins every pod to be built via framework.
Whilst this is supported for ParseUI - it's not supported by Parse.framework itself (it's coming soon...).

I would recommend using a pre-built binary right now or sub-project referencing instead of beta of cocoapods.

**Comment by skhavari** [comment]
thanks.  will go with one of the options you mention and will be looking out for framework support in Parse.
